{
 "title": "Soft Arch",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "query": "label_values(starlette_request_duration_seconds_bucket, path)"
   },
   {
    "name": "method",
    "query": "label_values(starlette_request_duration_seconds_bucket, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency $method $path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, ( sum by (le)( rate(starlette_request_duration_seconds_bucket{path=\"$path\", method=\"$method\"}[1m])))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, ( sum by (le)( rate(starlette_request_duration_seconds_bucket{path=\"$path\", method=\"$method\"}[1m])))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, ( sum by (le)( rate(starlette_request_duration_seconds_bucket{path=\"$path\", method=\"$method\"}[1m])))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, ( sum by (le)( rate(starlette_request_duration_seconds_bucket{path=\"$path\", method=\"$method\"}[1m])))) * 1000",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, ( sum by (le)( rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, ( sum by (le)( rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, ( sum by (le)( rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, ( sum by (le)( rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000",
     "legendFormat": "1.0"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{path=\"/users\", method=\"POST\"}[1m]))",
     "legendFormat": "POST /users"
    },
    {
     "expr": "sum(rate(starlette_requests_total{path=\"/users\", method=\"GET\"}[1m]))",
     "legendFormat": "GET /users"
    },
    {
     "expr": "sum(rate(starlette_requests_total{path=\"/users/{user_id}\", method=\"GET\"}[1m]))",
     "legendFormat": "GET /users/{user_id}"
    },
    {
     "expr": "sum(rate(starlette_requests_total{path=\"/users/{user_id}\", method=\"PUT\"}[1m]))",
     "legendFormat": "PUT /users/{user_id}"
    },
    {
     "expr": "sum(rate(starlette_requests_total{path=\"/users/{user_id}\", method=\"DELETE\"}[1m]))",
     "legendFormat": "DELETE /users/{user_id}"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (increase(starlette_requests_total{status_code=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ngonx Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  }
 ]
}